(() => {
 "use strict";
 const colors=[['코랄 / Coral','--color-coral'],['스카이 블루 / Sky','--color-sky'],['버터 옐로 / Butter','--color-butter'],['주요 행동 / Action','--color-action'],['본문 / Text','--color-text'],['보조 문구 / Muted','--color-text-muted'],['기본 배경 / Surface','--color-surface'],['캔버스 / Canvas','--scene-background'],['활성 경로 / Active','--scene-active']];
 const computed=getComputedStyle(document.documentElement);
 colors.forEach(([label,token])=>{const card=document.createElement('div');card.className='ds-swatch';const color=document.createElement('div');color.className='ds-swatch-color';color.style.setProperty('--swatch','var('+token+')');const copy=document.createElement('div');copy.className='ds-swatch-copy';const title=document.createElement('strong');title.textContent=label;const name=document.createElement('code');name.textContent=token;const value=document.createElement('code');value.textContent=computed.getPropertyValue(token).trim();copy.append(title,name,value);card.append(color,copy);document.getElementById('ds-swatches').append(card);});
 [1,2,3,4,6,8,12,16].forEach(size=>{const item=document.createElement('div');item.className='ds-spacing-item';const bar=document.createElement('div');bar.className='ds-spacing-bar';bar.style.setProperty('--sample-space','var(--space-'+size+')');const label=document.createElement('span');label.textContent=size*4+'px';item.append(bar,label);document.getElementById('ds-spacing').append(item);});
 document.getElementById('ds-selected').addEventListener('click',event=>{const button=event.currentTarget;const active=button.getAttribute('aria-pressed')!=='true';button.setAttribute('aria-pressed',String(active));button.textContent=active?'선택됨':'선택 안 됨';});
 document.getElementById('ds-form').addEventListener('submit',event=>{event.preventDefault();const status=document.getElementById('ds-form-status');status.hidden=false;status.textContent='입력 형식을 확인했습니다. 실제 전송은 하지 않았습니다.';});
 const dialog=document.getElementById('ds-dialog'),opener=document.getElementById('ds-open-dialog');opener.addEventListener('click',()=>dialog.showModal());dialog.querySelectorAll('[data-ds-close]').forEach(button=>button.addEventListener('click',()=>dialog.close()));document.getElementById('ds-confirm').addEventListener('click',()=>dialog.close());dialog.addEventListener('close',()=>opener.focus());
 let zoom=1,x=0,y=0,drag=null;const graph=document.getElementById('ds-graph'),pan=document.getElementById('ds-pan');
 function render(){graph.style.transform='translate('+x+'px,'+y+'px) scale('+zoom+')';document.getElementById('ds-zoom-level').textContent=Math.round(zoom*100)+'%';document.getElementById('ds-zoom-in').disabled=zoom>=1.6;document.getElementById('ds-zoom-out').disabled=zoom<=.6;}
 document.getElementById('ds-zoom-in').addEventListener('click',()=>{zoom=Math.min(1.6,zoom+.2);render();});document.getElementById('ds-zoom-out').addEventListener('click',()=>{zoom=Math.max(.6,zoom-.2);render();});document.getElementById('ds-reset').addEventListener('click',()=>{zoom=1;x=0;y=0;render();});
 pan.addEventListener('pointerdown',event=>{if(event.button!==0)return;drag={x:event.clientX,y:event.clientY,baseX:x,baseY:y};pan.setPointerCapture(event.pointerId);});pan.addEventListener('pointermove',event=>{if(!drag)return;x=drag.baseX+event.clientX-drag.x;y=drag.baseY+event.clientY-drag.y;render();});['pointerup','pointercancel','lostpointercapture'].forEach(type=>pan.addEventListener(type,()=>drag=null));
 let english=false,workshop=null;const link=document.getElementById('ds-workshop');document.getElementById('ds-language').addEventListener('click',event=>{english=!english;event.currentTarget.textContent=english?'한국어':'English';event.currentTarget.setAttribute('aria-pressed',String(english));link.textContent=english?'Workshop':'워크숍';});link.addEventListener('click',event=>{if(!workshop||workshop.closed){workshop=window.open(link.href,'worflogy-workshop');if(!workshop)return;workshop.opener=null;}event.preventDefault();workshop.focus();});
})();

(()=>{let floor=1;const up=document.getElementById('ds-floor-up'),down=document.getElementById('ds-floor-down'),out=document.getElementById('ds-floor-position');if(!up)return;function render(){up.disabled=floor===1;down.disabled=floor===3;out.textContent='0'+floor+' / 03';}up.onclick=()=>{floor--;render();};down.onclick=()=>{floor++;render();};render();})();

document.getElementById("ds-glass-play")?.addEventListener("click",()=>{document.getElementById("ds-glass-status").textContent="PLAY 동작을 확인했습니다. 이 화면은 컴포넌트 예시입니다.";});
