/* English canvas narration and object descriptions. */
window.WORFLOGY_COPY = {
    "names":  {
                  "ontology":  "Ontology · Semantic Cosmos",
                  "holistic":  "Holistic Interpretation",
                  "dynamics":  "System Dynamics Design",
                  "signal":  "Weak Signal Theory",
                  "linked":  "Top-Down · Network Reinforcement",
                  "semantics":  "Semantics",
                  "worflogy":  "WORFLOGY · Bottom-Up Network Growth",
                  "agent":  "AI Agent",
                  "knowledge":  "Ontology Knowledge Graph",
                  "rag":  "Knowledge Graph RAG · Ontology Reasoning",
                  "simulation":  "System Dynamics · Risk Simulation",
                  "api":  "External Data API",
                  "content":  "Game Content",
                  "incubation":  "Game Incubation · Ontology Reasoning",
                  "competency":  "Competency Evaluation · Ontology Reasoning",
                  "policy":  "Engineering Process Policy · Ontology Reasoning",
                  "profile":  "Profile \u0026 Career",
                  "events":  "Events \u0026 Issues",
                  "position":  "Position Recommendation",
                  "guide":  "WBS-Based Work \u0026 Communication Guide",
                  "growth":  "Position Growth Monitoring",
                  "report":  "Execution Report",
                  "start":  "External Query",
                  "core":  "Design",
                  "alternative":  "Alternative Strategy",
                  "chosen":  "Selected Strategy",
                  "review":  "Review",
                  "feedback":  "Feedback"
              },
    "overrides":  {
                      "platform":  {
                                       "profile":  "HR Profile \u0026 Career",
                                       "events":  "Jira / GitHub Events \u0026 Voice of Customer",
                                       "position":  "Profile Diagnosis \u0026 Position Recommendation",
                                       "guide":  "WBS Matching \u0026 Position-Based Work Guidance",
                                       "report":  "Event \u0026 Issue Response Report",
                                       "growth":  "Position Growth Monitoring",
                                       "competency":  "Work Competency Diagnosis · Ontology Engine",
                                       "policy":  "Engineering Process Policy Guidance · Ontology Engine",
                                       "agent":  "AI Agent · User Interaction Interface",
                                       "knowledge":  "Accumulated Experience · Knowledge Graph"
                                   },
                      "problem":  {
                                      "start":  "A Problem",
                                      "core":  "Team Deliberation",
                                      "alternative":  "Promising Unselected Strategies",
                                      "chosen":  "Chosen Strategy",
                                      "report":  "Tasks \u0026 Response Reports",
                                      "review":  "Peer Review \u0026 Evaluation",
                                      "feedback":  "Official Policy",
                                      "rag":  "Knowledge Graph RAG Ontology Engine",
                                      "agent":  "AI Agent",
                                      "knowledge":  "Collaboration Knowledge Graph"
                                  },
                      "risk":  {
                                   "start":  "A Project Risk",
                                   "core":  "Risk Diagnosis \u0026 Feasible Strategies",
                                   "alternative":  "Promising Unselected Strategies",
                                   "chosen":  "Chosen Risk Response",
                                   "report":  "Tasks \u0026 Work Reports",
                                   "review":  "Expert Mentoring",
                                   "feedback":  "Adopted Risk Policy",
                                   "simulation":  "System Dynamics Risk Simulation Engine",
                                   "rag":  "Knowledge Graph RAG Ontology Engine",
                                   "agent":  "AI Agent",
                                   "knowledge":  "Risk Optimization Knowledge Graph"
                               },
                      "research":  {
                                       "start":  "Research Topic",
                                       "core":  "Content \u0026 Causal Relationships",
                                       "alternative":  "Purchase \u0026 Improvement",
                                       "chosen":  "Sold Experimental Design",
                                       "report":  "Agreement \u0026 Contested Points",
                                       "review":  "Content Analysis",
                                       "feedback":  "AI Partner Suggestions",
                                       "api":  "External Scholarly Data API",
                                       "rag":  "Knowledge Graph RAG Ontology Engine"
                                   },
                      "narrative":  {
                                        "start":  "Literary \u0026 Non-Literary Sources",
                                        "core":  "World Building, Scenario \u0026 NPC Creation",
                                        "alternative":  "Editing",
                                        "chosen":  "Game Content SDK",
                                        "report":  "Play Logs",
                                        "review":  "Narrative Analysis",
                                        "feedback":  "Scenario \u0026 NPC Reconstruction",
                                        "content":  "Game Content",
                                        "rag":  "Knowledge Graph RAG Ontology Engine"
                                    },
                      "npc":  {
                                  "start":  "Game Character",
                                  "core":  "System Dynamics \u0026 Top-Down Static Knowledge Graph",
                                  "alternative":  "Simulation",
                                  "chosen":  "Game Content SDK",
                                  "report":  "Play Logs",
                                  "review":  "Decision Analysis",
                                  "feedback":  "Game Character Update",
                                  "content":  "Game Content",
                                  "rag":  "Knowledge Graph RAG Ontology Engine"
                              },
                      "creator":  {
                                      "start":  "Solo Game Content Developer",
                                      "core":  "Game \u0026 Market Analysis · Quantitative Targets",
                                      "alternative":  "Mentoring",
                                      "chosen":  "Game Content SDK",
                                      "report":  "Metric Collection",
                                      "review":  "Metric Analysis",
                                      "feedback":  "Growth Guidance · Trends · Target Reset",
                                      "content":  "Game Content",
                                      "api":  "Game Content Statistics API",
                                      "incubation":  "Game Incubation Ontology Engine",
                                      "rag":  "Knowledge Graph RAG Ontology Engine"
                                  }
                  },
    "overview":  [
                     "First, compose a semantic cosmos through traditional Top-Down design.",
                     "Observe phenomena together and interpret them as a whole.",
                     "Structure that interpretation from the top down.",
                     "Reinforce connections within the existing network. The network strengthens through repeated cycles.",
                     "Collect the semantics produced through Top-Down design.",
                     "Top-Down semantics compose a complete semantic cosmos.",
                     "Traditional Top-Down: semantic technology oriented toward network reinforcement.",
                     "Now begin a separate semantic cosmos using WORFLOGY’s Bottom-Up design.",
                     "Observe and interpret the phenomena as a whole.",
                     "Reconstruct holistic interpretation through system dynamics design.",
                     "Weak signal theory also influences system dynamics design.",
                     "New nodes and relationships emerge repeatedly. This is a network growth loop.",
                     "Collect the semantics produced through Bottom-Up design.",
                     "Bottom-Up semantics compose a complete semantic cosmos of their own.",
                     "Invented by WORFLOGY: Bottom-Up semantic technology oriented toward network growth."
                 ],
    "descriptions":  {
                         "ontology":  "Each approach can compose a semantic cosmos. Watch Top-Down complete one first, then WORFLOGY’s Bottom-Up compose one separately.",
                         "holistic":  "An observation lens brings different phenomena into one field of interpretation.",
                         "dynamics":  "System dynamics design is informed by holistic interpretation and weak signal theory, and influences Bottom-Up design.",
                         "signal":  "Weak signal theory influences system dynamics design.",
                         "linked":  "Top-Down structures interpretation from above. Its loop reinforces the existing network.",
                         "worflogy":  "Invented by WORFLOGY. System dynamics, informed by holistic interpretation and weak signals, shapes a repeating network growth loop. Original IP secured in 2017.",
                         "semantics":  "Meaningful relationships produced through the active design approach compose its ontology.",
                         "agent":  "The user interacts through the AI agent, which receives relevant context from the knowledge graph.",
                         "knowledge":  "The resulting ontology knowledge graph."
                     },
    "queries":  {
                    "platform":  "Help me assign people and guide work for this project.",
                    "problem":  "Help me find a strategy to solve this problem.",
                    "risk":  "Help me diagnose the risks in this project.",
                    "research":  "Help me design an experiment for this research topic.",
                    "narrative":  "Help me build a game world, scenarios and NPCs from these sources.",
                    "npc":  "Help me analyze this character’s decision-making tendencies.",
                    "creator":  "Help me set goals and growth metrics for my solo game project."
                },
    "objectDescriptions":  {
                               "platform":  {
                                                "profile":  "Evaluate a person’s profile and career against the engineering process.",
                                                "events":  "Jira or GitHub events and customer issues trigger a match to the relevant WBS.",
                                                "position":  "Recommend a suitable position and prepare to monitor the member’s growth.",
                                                "guide":  "Use the matching WBS and the recommended or actually assigned position to explain what to do, with whom, and how.",
                                                "report":  "Report the response taken following the work and communication guide.",
                                                "growth":  "Evaluate response reports and reflect the results in position growth monitoring.",
                                                "competency":  "An ontology engine diagnoses work competency and develops from accumulated knowledge-graph experience.",
                                                "policy":  "An ontology engine guides engineering process policies and develops from accumulated knowledge-graph experience.",
                                                "agent":  "The user interacts through the AI agent. The knowledge graph supplies context for understanding the situation and guiding the response.",
                                                "knowledge":  "Accumulate the workflow and its outcomes, then feed experience back into the AI agent and both ontology engines. The knowledge graph also provides relevant context directly to the AI agent."
                                            },
                               "problem":  {
                                               "start":  "A new problem brings the team together. For similar problems, established policy is recommended first.",
                                               "core":  "Team members develop competing strategies and choose through deliberation.",
                                               "alternative":  "Promising unselected strategies remain weak signals for continued review and may be recommended for a later problem.",
                                               "chosen":  "The strategy selected through team deliberation becomes executable tasks.",
                                               "report":  "Carry out the tasks and report their outcomes for peer review.",
                                               "review":  "Peers review and evaluate the reported outcomes before policy adoption.",
                                               "feedback":  "Adopt the validated approach as official policy and recommend it first for a similar problem.",
                                               "rag":  "Retrieve accumulated knowledge and grow the ontology with new concepts and relationships.",
                                               "agent":  "The user interacts through the AI agent. The knowledge graph supplies context for understanding the situation and guiding the response.",
                                               "knowledge":  "Connect collaboration, strategies, decisions, outcomes and policies; feed the growing knowledge back into the ontology engine. The knowledge graph also provides relevant context directly to the AI agent."
                                           },
                               "risk":  {
                                            "start":  "Diagnose a new project risk. For similar risks, retrieve and recommend previously adopted policy first.",
                                            "core":  "Diagnose the risk and compare feasible response strategies using system dynamics simulation.",
                                            "alternative":  "Retain promising unselected strategies as weak signals. Reconsider and recommend them when a later risk context makes them relevant.",
                                            "chosen":  "Select a feasible strategy and turn it into tasks.",
                                            "report":  "Execute the risk response tasks and report their outcomes for expert mentoring.",
                                            "review":  "The mentor who provided the risk simulation know-how reviews the work and guides the team before policy adoption.",
                                            "feedback":  "Adopt the validated risk response after mentoring and reuse it as policy for similar project risks.",
                                            "simulation":  "Represent system dynamics stocks, flows and feedback; compare illustrative risk scenarios over time.",
                                            "rag":  "Retrieve accumulated risk knowledge and dynamically grow the ontology with new concepts and relationships.",
                                            "agent":  "The user interacts through the AI agent. The knowledge graph supplies context for understanding the situation and guiding the response.",
                                            "knowledge":  "Connect diagnosis, strategies, execution, mentoring and policy; feed this experience back into the RAG ontology engine. The knowledge graph also provides relevant context directly to the AI agent."
                                        },
                               "research":  {
                                                "agent":  "The user interacts through the AI agent. The knowledge graph supplies context for understanding the situation and guiding the response.",
                                                "knowledge":  "The knowledge graph also provides relevant context directly to the AI agent.",
                                                "start":  "A research topic initiates notebook authoring and suggestions from the AI partner.",
                                                "core":  "Write research content and define causal relationships. Improve the design through purchased-design improvements and AI partner suggestions.",
                                                "alternative":  "Purchase and improve designs; feed improvements back into the research content and causal model.",
                                                "chosen":  "A sold experimental design provides the basis for agreement and contested points.",
                                                "report":  "Agreement and contested points feed content analysis, which informs AI partner suggestions for the next design.",
                                                "review":  "Analyze the content of agreement and contested points to inform the AI partner suggestions.",
                                                "feedback":  "Propose changes informed by the research topic and content analysis; feed suggestions back into the experimental design.",
                                                "api":  "External scholarly data supports the AI agent and connects with the RAG ontology engine.",
                                                "rag":  "Retrieve research knowledge and dynamically grow the ontology from accumulated designs and feedback."
                                            },
                               "narrative":  {
                                                 "agent":  "The user interacts through the AI agent. The knowledge graph supplies context for understanding the situation and guiding the response.",
                                                 "knowledge":  "The knowledge graph also provides relevant context directly to the AI agent.",
                                                 "start":  "Literary and non-literary material feeds world building, scenario development and NPC creation.",
                                                 "core":  "Develop the world, scenario and NPCs. Incorporate edits and reconstructed scenarios and NPCs.",
                                                 "alternative":  "Edit the narrative and feed revisions back into development.",
                                                 "chosen":  "Connect developed narrative content to the game content SDK, leading to gameplay and play logs.",
                                                 "report":  "Collect gameplay logs for narrative analysis.",
                                                 "review":  "Analyze play logs to inform scenario and NPC reconstruction.",
                                                 "feedback":  "Reconstruct scenarios and NPCs using narrative analysis, then return them to development.",
                                                 "content":  "Game content supports the AI agent and connects with the RAG ontology engine.",
                                                 "rag":  "Retrieve narrative knowledge and grow the ontology from accumulated development and gameplay experience."
                                             },
                               "npc":  {
                                           "agent":  "The user interacts through the AI agent. The knowledge graph supplies context for understanding the situation and guiding the response.",
                                           "knowledge":  "The knowledge graph also provides relevant context directly to the AI agent.",
                                           "start":  "A game character enters the modeling and incubation workflow.",
                                           "core":  "Model the character with system dynamics and a Top-Down static knowledge graph. Incorporate simulation feedback and character updates.",
                                           "alternative":  "Simulate character behavior and decisions; return feedback to the model.",
                                           "chosen":  "Connect the modeled character to the game content SDK for gameplay.",
                                           "report":  "Gameplay logs record character behavior and decisions for analysis.",
                                           "review":  "Analyze decisions in the play logs to inform character updates.",
                                           "feedback":  "Update the character using decision analysis and feed it back into the model.",
                                           "content":  "Game content supports the agent and connects to the RAG ontology engine.",
                                           "rag":  "Accumulated character experience grows the ontology, supporting later retrieval and reasoning."
                                       },
                               "creator":  {
                                               "agent":  "The user interacts through the AI agent. The knowledge graph supplies context for understanding the situation and guiding the response.",
                                               "knowledge":  "Development experience grows both the game incubation and RAG ontology engines, and provides context to the AI agent.",
                                               "start":  "A solo developer begins with game content and its market context.",
                                               "core":  "Analyze the game and market, set quantitative targets, and refine them through mentoring and growth guidance.",
                                               "alternative":  "Mentoring feeds improvements back into analysis and target setting.",
                                               "chosen":  "Connect game content to the SDK to collect metrics.",
                                               "report":  "Collect quantitative metrics and pass them to metric analysis.",
                                               "review":  "Analyze collected metrics to inform growth guidance, trends and revised targets.",
                                               "feedback":  "Guide growth, analyze trends and reset quantitative targets for the next game and market analysis cycle.",
                                               "content":  "Game content supports the AI agent and connects with game content statistics.",
                                               "api":  "Game content statistics connect to the content and game incubation ontology engine.",
                                               "incubation":  "The game incubation ontology engine connects statistics with the RAG ontology engine. Accumulated development knowledge dynamically grows this engine.",
                                               "rag":  "Development knowledge grows the ontology and supports retrieval and reasoning."
                                           }
                           }
};