import {liveComponentsGuide,bindLiveComponentsGuide} from './live-components-guide.js';
import {graphicGuide} from './graphic-guide.js';
import { implementedGuide, bindImplementedGuide } from './implemented-guide.js';
import './game-hud.css';
import './preparation.css';
import { artGuide } from './art-guide.js';
import { symbol, apPips } from './symbols.js';
import './style.css';
import './design-system.css';
import './readability.css';
import './tactical-finish.css';
import { themeColor } from './theme.js';
const colors=[['paper-bg','Paper canvas','준비 화면 배경'],['paper-surface','Paper surface','작전 서류'],['paper-ink','Paper ink','준비 화면 글자'],['paper-frame','Ink frame','강한 프레임'],['paper-action','Order','준비 화면 주요 행동'],['faction-human','Human','인간 진영 소속'],['faction-ai','Collective','AI 진영 소속'],['bg','Canvas','전체 배경'],['surface','Surface','패널 · 대화상자'],['text','Ink','주요 텍스트'],['accent','Cobalt','선택 · 주요 행동'],['info','Ice Signal','정보 · 네트워크'],['warning','Amber','주의 · 자원'],['danger','Hostile','적 · 위험'],['memory','Memory','기억 · 목표 노드']];
document.querySelector('#design-system').innerHTML=`
<header><a class="brand wordmark" href="./"><span aria-hidden="true">N∕</span><b>NULL SECTOR</b></a><nav><a href="#art-direction">아트 방향</a><a href="#foundation">기초 규칙</a><a href="#components">컴포넌트</a><a href="#tactical">전술 정보</a></nav><a class="ds-back" href="./">게임으로 돌아가기</a></header>
<div class="ds-layout"><aside class="ds-sidebar"><span class="eyebrow">INK TACTICS / 04</span><a href="#intro">개요</a><a href="#art-direction">00 공식 아트 방향</a><a href="#foundation">01 색상</a><a href="#typography">02 타이포그래피</a><a href="#spacing">03 간격과 형태</a><a href="#components">04 행동과 상태</a><a href="#tactical">05 전술 컴포넌트</a><a href="#implemented">06 실제 화면 컴포넌트</a><a href="#screen-rules">07 화면과 상태 규칙</a><a href="#delivery">08 제작·검수 기준</a><p>Windows · Chrome / Edge<br>Light theme · v4.0</p></aside><article class="ds-content">
<section class="ds-hero" id="intro"><div><span class="ds-badge">LIGHT INTERFACE SYSTEM</span><h1>명확한 정보.<br><em>선명한 판단.</em></h1><p>가상 전장의 복잡함을 정돈하는 밝은 인터페이스.<br>배경은 조용하게, 행동과 상태는 분명하게 표현합니다.</p></div><div class="ds-hero-mark" aria-hidden="true"><div class="ds-cross">+</div><div class="ds-radar"></div><span>NULL / SECTOR<br>TACTICAL SYSTEMS</span></div></section>
${artGuide}
<section id="foundation"><div class="ds-heading"><span>01 / FOUNDATION</span><h2>색상은 역할을 갖습니다.</h2><p>기본 색상 토큰입니다. 최신 전투 HUD는 아래 07의 종이색·청회색 잉크·황동색 강조를 사용합니다. 진영 고유색과 적·아군 상태 색은 다른 역할입니다. 아래 값은 실제 CSS 토큰에서 읽습니다.</p></div><div class="ds-swatches">${colors.map(([token,name,label])=>`<div class="ds-swatch"><div style="background:var(--${token})"></div><strong>${name}</strong><span>${label}</span><code>${themeColor(token).toUpperCase()}</code></div>`).join('')}</div><div class="ds-status-row"><span class="ds-badge success">${symbol('check')} 연결됨</span><span class="ds-badge info">${symbol('info')} 표적 정보 확보</span><span class="ds-badge warning">${symbol('warning')} 행동력 부족</span><span class="ds-badge danger">${symbol('target')} 적 신호 탐지</span></div></section>
<section id="typography"><div class="ds-heading"><span>02 / TYPOGRAPHY</span><h2>읽는 순서가 곧 정보의 위계.</h2><p>제목은 도현체, 영문 HUD는 Oxanium, 본문은 Noto Sans KR. 게임에 포함된 폰트로 표시합니다.</p></div><div class="ds-type"><div><code>DO HYEON / 38–60</code><p class="ds-display">기억은 남는다.</p></div><div><code>DO HYEON / 24</code><p class="ds-title">기억의 격리 구역</p></div><div><code>NOTO SANS KR / 14</code><p class="ds-body">동쪽 노드에서 메모리를 확보하고 진입 구역으로 복귀하세요.</p></div><div><code>NOTO SANS KR / 12</code><p class="ds-caption">선택한 요원 · 행동력 2 / 2 · 무결성 9 / 9</p></div><div><code>OXANIUM / 16</code><p class="ds-mono">GHOST &nbsp; 07:12 &nbsp; 85% &nbsp; 02 AP</p></div></div></section>
<section id="spacing"><div class="ds-heading"><span>03 / SPACE & SHAPE</span><h2>각진 프레임과 읽기 쉬운 간격.</h2></div><div class="ds-space">${[4,8,12,16,24,32,48,64].map(n=>`<div><i style="height:${n}px"></i><code>${n}</code></div>`).join('')}</div><div class="ds-radius"><div style="border-radius:var(--radius-paper)">0px<small>진영 · 서류 · 편성</small></div><div style="border-radius:var(--radius-hud)">2px<small>전투 카드 · 행동</small></div><div style="border-radius:var(--radius-sm)">4px<small>공통 보조 버튼 · 배지</small></div></div></section>
<section id="components"><div class="ds-heading"><span>04 / COMPONENTS</span><h2>모든 행동에 같은 문법.</h2><p>공통 기본 상태입니다. 실제 준비 화면은 0px, 전투 화면은 2px 모서리를 적용합니다. 아래 06 영역에서 현재 게임의 변형을 확인하세요. Tab 키로 포커스를 확인할 수 있습니다.</p></div><div class="ds-demo"><div class="ds-demo-label">BUTTONS</div><div class="ds-button-row"><button class="primary" data-demo="작전 개시 버튼">작전 개시</button><button data-demo="파일 저장 버튼">파일로 저장</button><button class="ds-quiet" data-demo="보조 행동">취소</button><button disabled>행동력 부족</button></div></div><div class="ds-demo"><div class="ds-demo-label">ACTION STATES</div><div class="ds-button-row"><button class="action" data-demo="이동"><span>01</span><strong>이동</strong><small>1 AP</small></button><button class="action active" aria-pressed="true" data-demo="선택된 사격"><span>02 · 선택됨</span><strong>사격</strong><small>1 AP</small></button><button class="action" disabled><span>04</span><strong>정밀 관통</strong><small>2턴 대기</small></button></div></div><div id="ds-feedback" class="ds-feedback" role="status">${symbol('info')} 버튼을 누르면 이곳에서 상태 메시지를 확인할 수 있습니다.</div></section>
${liveComponentsGuide}
${graphicGuide}${implementedGuide}<div class="ds-end"><span>NULL SECTOR / INK TACTICS 4.0</span><a href="./">전장으로 돌아가기</a></div></article></div><div class="ds-ownership">© 2025 워플로지(WORFLOGY). All rights reserved.</div>`;
bindImplementedGuide();bindLiveComponentsGuide();
document.addEventListener('click',e=>{const b=e.target.closest('[data-demo]');if(b)document.querySelector('#ds-feedback').textContent=`확인: ${b.dataset.demo} — 디자인 시스템 상태 미리보기입니다.`;});


