import { chromium } from '@playwright/test';
import { mkdir } from 'node:fs/promises';
import assert from 'node:assert/strict';
import { newGame, packSave } from '../src/rules.js';
await mkdir('output',{recursive:true});
for(const channel of ['chrome','msedge']){
 const browser=await chromium.launch({channel,headless:true});
 try{
  const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];
  page.on('pageerror',e=>errors.push(e.message));
  await page.goto('http://127.0.0.1:5173/');
  await page.waitForFunction(()=>!!window.__game,{timeout:60000});
  await page.locator('#skip-prologue').click();
  await page.screenshot({path:`output/${channel}-lobby.png`});
  await page.locator('[data-faction="human"]').click();
  assert.ok(await page.locator('#brief-objectives').textContent().then(t=>t.includes('노드')));
  await page.locator('#weapon').selectOption('precision');
  await page.locator('#module').selectOption('relay');
  await page.screenshot({path:`output/${channel}-briefing.png`,fullPage:true});
  await page.locator('#deploy').click();
  assert.equal(await page.evaluate(()=>__game.state.agents[0].weapon),'precision');
  assert.equal(await page.evaluate(()=>__game.state.agents[0].module),'relay');
  await page.locator('[data-action="skill"]').click();
  assert.equal(await page.evaluate(()=>__game.state.units[0].ap),1);
  assert.equal(await page.locator('.enemy-card').count(),8);
  await page.locator('[data-action="watch"]').click();
  assert.equal(await page.evaluate(()=>__game.state.units[0].watch),true);
  await page.screenshot({path:`output/${channel}-battle.png`});
  await page.locator('#end-turn').click();
  await page.waitForFunction(()=>__game.state.turn===2);
  await page.waitForFunction(()=>!document.querySelector('#end-turn').disabled);
  await page.waitForFunction(()=>document.querySelector('#save-status').textContent.includes('완료'));
  const state=await page.evaluate(()=>__game.state);
  await page.reload();await page.waitForFunction(()=>!!window.__game);await page.waitForFunction(()=>document.querySelector('#lobby').hidden);
  assert.deepEqual(await page.evaluate(()=>__game.state),state);
  const snapshot=newGame('human',[2,0,4,5]);snapshot.units[0].x=2;snapshot.units[0].z=2;
  await page.locator('#file').setInputFiles({name:'test-save.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(packSave(snapshot)))});
  await page.waitForFunction(()=>__game.state.units[0].role===2);
  await page.locator('[data-action="skill"]').click();
  const p=await page.evaluate(()=>__game.project(3,2)),bounds=await page.locator('#viewport').boundingBox();
  await page.mouse.click(bounds.x+p.x,bounds.y+p.y);
  await page.locator('#confirm-attack').click();
  await page.waitForFunction(()=>__game.state.cover.find(c=>c.id==='c3-2').hp===0);
  assert.ok(await page.evaluate(()=>__game.physicalBodies)>21);
  await page.screenshot({path:`output/${channel}-destruction.png`});
  await page.locator('[data-action="move"]').click();
  const move=await page.evaluate(()=>__game.project(3,2));await page.mouse.click(bounds.x+move.x,bounds.y+move.y);
  await page.waitForFunction(()=>__game.state.units[0].x===3);
  await page.locator('#file').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{"version":99}')});
  await page.waitForFunction(()=>document.querySelector('#toast').textContent.includes('지원하지'));
  assert.equal(await page.evaluate(()=>__game.state.units[0].role),2);
  await page.locator('#home').click();await page.locator('[data-faction="ai"]').click();await page.locator('#deploy').click();
  assert.equal(await page.evaluate(()=>__game.state.faction),'ai');
  assert.ok(await page.locator('[data-action="hack"]').isDisabled());
  const victory=newGame();victory.units[0].x=2;victory.units[0].z=1;victory.carrier='p0';
  await page.locator('#file').setInputFiles({name:'extraction.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(packSave(victory)))});
  await page.waitForFunction(()=>__game.state.carrier==='p0');
  const exit=await page.evaluate(()=>__game.project(1,1));await page.mouse.click(bounds.x+exit.x,bounds.y+exit.y);
  await page.waitForFunction(()=>__game.state.status==='won');
  assert.ok(await page.locator('#result').isVisible());
  await page.evaluate(()=>{window.showSaveFilePicker=undefined;});
  const downloadPromise=page.waitForEvent('download');await page.locator('#save').click();const download=await downloadPromise;assert.equal(download.suggestedFilename(),'null-sector-save.json');
  await page.screenshot({path:`output/${channel}-ai.png`});
  assert.deepEqual(errors,[]);
  console.log(`${channel}: lobby, faction, actions, enemy turn, local resume, valid/invalid file restore passed`);
 }finally{await browser.close();}
}
